[package]
name = "knx-cli"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "knx"
path = "src/main.rs"

[dependencies]
knx-app.workspace = true
knx-etsproj.workspace = true
knx-store.workspace = true
tempfile.workspace = true

[dev-dependencies]
tempfile.workspace = true
serde_json.workspace = true
zip.workspace = true
