#!/bin/bash
# KNXBench — SessionStart hook, registered in .claude/settings.json.
#
# Local sessions: exits immediately and prints nothing. Claude Code sets
# CLAUDE_CODE_REMOTE=true only in cloud sessions.
#
# Cloud sessions:
#   * sets the repository-local git identity required by AGENTS.md §Git;
#   * puts ~/.cargo/bin on PATH for later Bash commands (CLAUDE_ENV_FILE);
#   * installs the web frontend's locked npm tree if it is missing;
#   * prints tools/cloud/SESSION_RULES.md plus an environment report. The
#     SessionStart hook's plain stdout becomes context for the agent.
#
# It never fails the session: every problem is reported, not fatal.

[ "${CLAUDE_CODE_REMOTE:-}" = "true" ] || exit 0

repo="${CLAUDE_PROJECT_DIR:-$(pwd)}"
cd "$repo" || exit 0

git config user.name "KNXBench"
git config user.email "github@knxbench.com"

# The environment's setup script (tools/cloud/setup-env.sh) leaves
# /var/tmp/knxbench-cloud/setup.status behind. A session without it, or
# without WebKit, gets the same script run here once, so a missing or
# stale environment setup costs a minute instead of a whole session.
status_file="/var/tmp/knxbench-cloud/setup.status"
if [ -f "$status_file" ]; then
  setup_origin="ran as $(grep '^run_by=' "$status_file" | cut -d= -f2) at $(grep '^ran_at=' "$status_file" | cut -d= -f2)"
else
  setup_origin="NOT RUN by the environment (no $status_file)"
fi
fallback="not needed"
if ! pkg-config --exists webkit2gtk-4.1 2>/dev/null; then
  if [ "$(id -u)" = "0" ]; then
    runner=(bash)
  elif sudo -n true 2>/dev/null; then
    runner=(sudo -n bash)
  else
    runner=()
  fi
  if [ "${#runner[@]}" -gt 0 ]; then
    "${runner[@]}" tools/cloud/setup-env.sh session-start-fallback \
      >/tmp/knxbench-setup-fallback.log 2>&1
    fallback="ran setup-env.sh (log: /tmp/knxbench-setup-fallback.log)"
  else
    fallback="IMPOSSIBLE: not root and no passwordless sudo"
  fi
fi

if [ -d "$HOME/.cargo/bin" ]; then
  export PATH="$HOME/.cargo/bin:$PATH"
  if [ -n "${CLAUDE_ENV_FILE:-}" ]; then
    echo 'export PATH="$HOME/.cargo/bin:$PATH"' >>"$CLAUDE_ENV_FILE"
  fi
fi

npm_status="present"
if [ ! -d apps/knx-web/node_modules ]; then
  if (cd apps/knx-web && npm ci --no-audit --no-fund >/tmp/knxbench-npm-ci.log 2>&1); then
    npm_status="installed by npm ci"
  else
    npm_status="FAILED (see /tmp/knxbench-npm-ci.log)"
  fi
fi

cat tools/cloud/SESSION_RULES.md 2>/dev/null

echo
echo "## Environment report (generated by tools/cloud/session-start.sh)"
echo
echo "- rustc: $(rustc --version 2>/dev/null || echo 'MISSING — setup script did not install the toolchain')"
echo "- node: $(node --version 2>/dev/null || echo MISSING)"
echo "- apps/knx-web/node_modules: $npm_status"
echo "- environment setup: $setup_origin"
echo "- setup fallback in this hook: $fallback"
if [ -f "$status_file" ]; then
  echo "- last setup status: $(tr '\n' ' ' <"$status_file")"
fi
if pkg-config --exists webkit2gtk-4.1 2>/dev/null; then
  echo "- webkit2gtk-4.1: present (knx-desktop builds)"
else
  echo "- webkit2gtk-4.1: MISSING — report the two setup lines above; for apps/knx-web-only work, gate with --exclude knx-desktop on test AND clippy and say so in the PR"
fi
if [ -d OriginalData ]; then
  echo "- OriginalData/: PRESENT — stop and report this; the private corpus must never be in a cloud session"
else
  echo "- OriginalData/: absent (expected); corpus tests report as ignored"
fi
echo "- git identity: $(git config user.name) <$(git config user.email)>"
exit 0
